### ISSUE TITLE
[FEAT] Server 1차 과제

### ISSUE THREAD

**Issue by hellozo0** [DO-SOPT-SERVER/hellozo0#1]
## 📌  Feature Issue

세미나에 있는 health check API에 ResponseEntity 대신 응답 객체를 만들어, API를 리팩토링 해보세요. 

<조건>
1. 해당 응답 객체는 다른 API의 응답객체로도 활용될 수 있어야합니다.
예를 들어 이후에, 사용자 정보 조회 API를 만든다고 가정했을 때도 이 응답객체를 사용할 수 있어야 합니다.
2. health check를 리팩토링 한 API는 아래 응답예시를 응답 할 수 있어야합니다.
```javascript
{
 "code": 200,
 "status": "OK",
 "success": true
}
``` 

## 📝  To-do

- [x] Initializer에서 Spring 프로젝트 생성
- [x] 1주차 세미나 복습 겸 health check Controller 생성
- [x] ResponseEntity 대신 응답 객체를 만들기 ( 다른 API에도 사용할 수 있게 끔 만들기)
- [x] 응답 결과에 맞게끔 객체 수정
- [x] 키워드 과제 링크 READEME.md에 연결
