### ISSUE TITLE
[FEAT] Server 2차 과제

### ISSUE THREAD

**Issue by hellozo0** [DO-SOPT-SERVER/hellozo0#3]
## 📌  Feature Issue

1. 금일 세미나에서 사용한 DTO 클래스를 record로 모두 리팩토링 해주세요.
2. 사용자 수정, 삭제 API를 만들어주세요.
3. 그 외에 코드를 자유롭게 리팩토링을 해주신 뒤에, Pull Request에 어떤 리팩토링을 왜 진행했는지 작성해주세요!

어떤 것을 리팩토링 할 수 있을까요? 
아래 고려할 수 있는 기준들을 힌트삼아 진행하시면 될 것 같습니다. 할 수 있는 만큼 최대한 많이 해보시면 좋을 것 같습니다!

1. 변수명, 메소드명, 클래스명을 리팩토링한다.
2. 코드 컨벤션에 맞춰서 코드 스타일을 정리한다. → 코드를 더욱 깔끔하고 가독성 좋게 만들어보기.
3. 디자인 패턴을 적용해본다.
4. 로직을 개선해본다.
5. 최적화를 진행해본다. → 더 성능좋은 코드 또는 불필요한 코드 제거.
6. 세미나에서 다루지 않은 다양한 옵션들을 적용해본다.
7. 패키지 구조와 이름을 변경해본다.

## 📝  To-do

- [x] 키워드 과제 링크 READEME.md에 연결
- [x] PR에 API Test 결과 첨부하기
- [x] 과제 프로젝트 폴더 새로 생성해서 따로 관리하기
- [x] DTO --> record로 모두 리팩토링 *record에 대해 알아보기
- [x] 수정& 삭제 API 만들기
- [x] 생성 부분 리팩토링 해보기 왜, 어떤 리팩토링을 했는지 기재
