### ISSUE TITLE
[FEAT] Server 3차 과제

### ISSUE THREAD

**Issue by hellozo0** [DO-SOPT-SERVER/hellozo0#5]
## 📝  To-do

- [x] 키워드 과제 리드미에 연결
- [ ] 기본과제 
- [ ] 심화 세미나 코드 구현
- [ ] 심화과제 - 리팩토링 ( ApiResponse 부분 정교하게!)
